### ISSUE TITLE
Unable to run via bash shell

### ISSUE THREAD

**Issue by jumpmancol** [rockymadden/slack-cli#27]
I am able to initialize just fine, but I always get Sending: fail when it runs in a bash shell.  The same command works fine from the command line, just not from a bash shell.  The script I am kicking off is below, including the full output I get...

SCRIPT
export PATH=/usr/local/bin:$PATH;
slack init --channel='sickbeard-results' --token=<mytokenwashere>
slack send 'Starting Sickbeard'

OUTPUT
Initializing: done
Sending: fail

**Comment by emilv** [comment]
Do you have Curl installed?

**Comment by rockymadden** [comment]
I believe this is because of the pipe friendly nature of slack-cli. For the current pipe detection, it looks the same as someone trying to pipe in something to it, preferring that (but obviously not finding anything). For the time being, you can explicitly provide the message via `--message='Starting Sickbear'` until I put a better detection mechanism in place.

**Comment by rockymadden** [comment]
Found and squashed the bug causing this issue in `v0.10.0`. Thanks, again, for the report!
